#!/usr/bin/env -S sh -eu

# Add a thick, border around a video, as if we were to scale the video
# down, toward the frame center.

if [ "$#" -eq 0 ]
then
	>&2 printf "%s\n" "usage: ${0##*/} FILE..."
	exit 1
fi

for f
do
	g="${f%.*}.${0##*/}.mp4"

	x="0.75"
	c="black"

	ffmpeg -i "$f" -vf " \
	    pad=             \
	        w=iw/$x:     \
	        h=ih/$x:     \
	        x=(ow-iw)/2: \
	        y=(oh-ih)/2: \
	        color=$c     \
	" "$g"

	printf "%s\n" "${0##*/}: wrote to '$g'"
done
