#!/usr/bin/env -S sh -eu

# Stitch MP4 arguments, in order.

if [ "$#" -lt 2 ]
then
	>&2 printf "%s\n" "usage: ${0##*/} FILE FILE..."
	exit 1
fi

g="$(printf "%s" "$1$(shift; printf ":%s" "$@")")"
MP4Box $(printf -- "-cat %s " "$@") "$g"
printf "%s\n" "${0##*/}: wrote to '$g'"

