from typing import final, override

from lib import MetaScene, Paths, Wuf, slidesf

asset = Paths.assetf(__file__)


@final
class PacchikariInAgra(MetaScene):
    voiceover = asset("voiceover.wav")

    @override
    def scene(self, wuf: Wuf) -> None:
        ts = [
            25.2,  # Hello, my name is Lola Cindric. [...] between 1840 and 1914.
            30.1,  # In 1860, Lady Canning, the viceroy of India, was living in...
            32.1,  # ...Kolkata, when she entrusted...
            35.1,  # ...Marian Loveday Murray, a female British resident of...
            44.2,  # ...Agra, with the mission [...] these objects were borrowed from...
            49.3,  # ...the Taj Mahal, which had been built more than 200 years earlier.
            58.2,  # The correspondence between Canning and Murray [...] accompanied by...
            77.2,  # ...Nathu Ram, the owner of [...] the wife of the Scottish surgeon...
            86.3,  # ...John Murray, who remained famous [...] for being a photographer.
            90.0,  # John Murray's extant photographic work includes some of...
            106.4,  # ...the earliest images of Mughal monuments [...] after the reign of...
            115.2,  # ...the Mughal emperor Aurangzeb. [...] a few patrons during...
            138.1,  # ...the second half of the 18th century [...] adorn domestic interiors.
            151.3,  # Patterns from the Taj Mahal [...] ancient Greek mythology and decorated with...
            173.2,  # ...flower and gray patterns [...] let us first explore...
            207.0,  # ...the Mughal craft of stone inlaying. [...] the reign of the emperor Shah Jahan.
            231.0,  # Particularly time consuming, [...] one element among others, constituting...
            274.3,  # ...the singular and lavish character [...] in tabletops and cabinets, including in...
            327.4,  # ...the famous grade bookcase [...] a faraway and unintelligible world.
            404.1,  # One of these attempts [...] most especially from...
            410.1,  # ...the cenotaph, so Shah Jahan and his wife Mumtaz Mahal inside the Taj Mahal.
            428.1,  # These cenotaphs are composed [...] characteristic of Mughal art in general.
            437.3,  # As archival sources, [...] the Taj Mahal's Pacchikari program...
            439.2,  # ...sequenced in drawings...
            440.3,  # ...decline in various...
            443.2,  # ...scales of detailed views.
            459.0,  # These visual renditions on paper [...] included most prominently...
            553.3,  # ...paperweights, trays, plates, vases [...] British patrons selected...
            559.0,  # ...Pacchikari patterns from the Taj Mahal cenotaph, [...] copied and interchangeably...
            562.0,  # ...applied on domestic items familiar to them...
            582.0,  # ...such as this marble inlaid tabletop. [...] these objects is as follows...
            585.2,  # ...it first entails selecting patterns from the cenotaph...
            598.3,  # ...and copying them on a paper material; [...] into different compositions...
            603.1,  # ...and applied to homewares, as can be seen on this tray.
            616.2,  # The particular pattern of the Great Bundle [...] it has been extracted and rearranged...
            633.0,  # ...on an intricately inlaid inkstand [...] the main decorative pattern for...
            685.0,  # ...this tabletop, bearing in its center [...] the Victorian fascination with...
            693.0,  # ...miniaturization, as a few small scale models [...] These objects form part of...
            705.0,  # ...a wider production of miniature models [...] from the output of...
            734.0,  # ...the workshop of Nathu Ram, from whom [...] exotic designs and goods...
            825.0,  # ...to decorate its European interiors. [...] appropriation of its artistic productions.
            845.1,  # The tourist guide [...] This production process thus spotlights...
            856.0,  # ...the interconnectedness of local heritage [...] detected in Agra today...
            907.2,  # ...where the production of Pacchikari [...] elsewhere throughout the world.
            917.2,  # [References.]
            919.2,  # [Fade out.]
        ]

        slidesf(self, wuf, asset("slides/{}.png"), ts)


if __name__ == "__main__":
    PacchikariInAgra.run()
